### ISSUE TITLE
Thumbnail retrieved from wrong url

### ISSUE THREAD

**Issue by MartijnBraam** [armadillica/flamenco#116]
The thumbnails are not working in my job list. I've installed all 4 components on a VM in my home server.  I can connect to the dashboard on server-ip:8888 and adding a job works fine but the interface tries to load the thumbnail for the job from localhost:9999. It seems that it's not using the correct hostname for connecting from my laptop to the server.

The diagram in the blog post (http://gooseberry.blender.org/wp-content/uploads/2015/02/architecture_diagram-1024x576.png) implies the client only connects to the dashboard server (on port 8888). Letting the client connect to the server directly would be problematic if the laptop doesn't have access to the same lan as the server.

**Comment by Eibriel** [comment]
Hi! This is a known issue, the dashboard is loading the images directly from the server. Thanks for reporting!

**Comment by peppelinux** [comment]
My workaround was configure in manager application/config.py the public ip of the server, for example:

FLAMENCO_SERVER = '192.168.15.11:9999'

if all the client can reach this network, otherwise configure the server WAN interface and the problem were resolved.

surely, for avoids technical matters, using a VPN connection, with all the network routes propagated on each client, resolve definitely this kind of problem.

For Flamenco.io, a 0-coding GNU/Linux approach, could be the use of inotify for send (via scp, or whatever, NFS cp...) the thumbnail in a third-part storage each moment a new image will be stored in the folder monitored by inotify. This could patch this problem, with this flamenco.io version, in a production scenario.

**Comment by sybrenstuvel** [comment]
I'm closing this issue, since it relates to the old, now-obsolete version of Flamenco. Read about the new Flamenco 2.0 at https://flamenco.io/.
