### ISSUE TITLE
Manager: TypeError: : tuple indices must be integers, not str

### ISSUE THREAD

**Issue by tobimai** [armadillica/flamenco#140]
I installed all requiremenst with pip install -r requirements.txt
When I try to start the Manager this Message appears:

TypeError: : tuple indices must be integers, not str

I'm unsing Ubuntu 15.04 32bit.

**Comment by antonvdh** [comment]
I have the same problem : TypeError: <flask_script.commands.Command object at 0x2294510>: tuple indices must be integers, not str

**Comment by antonvdh** [comment]
Nobody?

**Comment by antonvdh** [comment]
Cannot reproduce the error.
But I still cannot run the manager. 
Please fix this because we cannot test:
TypeError: <flask_script.commands.Command object at 0x7ff7f63b2f10>: 'value' is an invalid keyword argument for JobType

**Comment by jeffbean** [comment]
This error is seen when `TaskManagementApi().get(job_types=",".join(worker.job_types_list))` returns anything but 200 or 404 as a status code.

**Comment by binarypearl** [comment]
I think I figured this out.  What's happening is that the 'Server' component is trying to write to '/' (at least on Linux.  It was erroring out on trying to get a lockfile.  So I looked at the code it was erroring out on:  vim /home/foo/dl/blender/Flamenco/flamenco-master/flamenco/server/application/modules/tasks/__init__.p

 And found this:
lock = LockFile("{0}server.lock".format(app.config['TMP_FOLDER']))

Ok, I'm like hmm, I I have no clue what that gets translated to.  So I put in a print statement and started it back up:
print ("SMM: " + "{0}server.local".format(app.config['TMP_FOLDER']))

And the result:
/tmpserver.local

Not to be confused with /tmp, which is world-writable, this is trying to write in /, which is only writable by root.

So I created that file as root, chown foo:foo, and then restarted it.  I saw it then errored out with another temporary directory it was trying to create in '/'.  So I did something you wouldn't normally do.  I did a chown foo:foo on '/'.  At this point, I'm willing to do whatever to get it working, however don't want to rely on this long-term. 

Now the Manager and Server have stopped giving a 500 Internal error.  And the job went to 'Active' in the Dashboard...and...and...now the Worker is crashing!  This is a separate issue, so I'll troubleshoot that separately.

Hope this helps,

--Shaun

**Comment by peppelinux** [comment]
just try to put a / there

lock = LockFile("{0}/server.lock".format(app.config['TMP_FOLDER']))

**Comment by fsiddi** [comment]
This was also a very trivial fix, sorry for holding off for so long. As I wrote in the commit log, the lockfile path was badly formatted and now it uses os.path.join, which reliably combines path segments. Let me know if you get any error!

**Comment by peppelinux** [comment]
It works but later, using master branch, I got, if I click on a worker, in the dashboard.
192.168.27.10 - - [06/Sep/2015 21:54:28] "GET /workers/view/1 HTTP/1.1" 404 -

If I click on a manager it works, but even if I changed his name "My Manager" to another, in application settings in dashboard this name remains unaltered... I think that it come from sqlite/mysql storage :)

There must be some configuration error because I can not use flamenco.io in production, I never seen a job in running state :( Actually I can't get it to work.

Probably there must be some SQL incoherence.
I really need to understand how to submit a job and some more documentation, some case of use.
Sorry for OT !

**Comment by peppelinux** [comment]
from manager stdout:
INFO:werkzeug:127.0.0.1 - - [06/Sep/2015 22:08:16] "GET /tasks/generate?worker=goose&uuid=579eaf884d6b11e583bd001cc4936120 HTTP/1.1" 404 -

from server stdout:
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:requests.packages.urllib3.connectionpool:"GET /tasks/generate?worker=goose&uuid=579eaf884d6b11e583bd001cc4936120 HTTP/1.1" 404 3
INFO:werkzeug:127.0.0.1 - - [06/Sep/2015 22:08:36] "GET /tasks/compiled/0?worker=goose HTTP/1.1" 400 -
INFO:werkzeug:127.0.0.1 - - [06/Sep/2015 22:08:41] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Sep/2015 22:08:41] "POST /workers HTTP/1.1" 204 -

**Comment by binarypearl** [comment]
A 404 message here doesn't necessarily indicate a problem.  What I have noticed is that is the 'Server' and 'Manager' constantly poll for new requests, and they return 404, as in 'I have nothing new to do'.  For me, I'm getting similar output to what you have, except that the Server and Manager output is flipped for me.

I documented the entire process I went through to create a working 4 node cluster (I added the 4th node after this post):  https://ontheothersideofthefirewall.wordpress.com/2015/09/05/blender-flamenco-3-node-cluster-working/

It's raw, but hopefully I ran into the issue(s) you are having and might have a solution there. 

I am running Linux as a master with Dashboard/Manager/Server/Worker.  I also have an OS X, Windows 10, and another Linux 'Worker'.  

A couple things that you might be running into:
1. Check to see if the 'Worker' crashed.  When configuring the 'Manager' for the first time, I wasn't sure what it wanted (the prompts actually want the path to the Blender binary).  So I had wrong values in here.  What happens is that the Worker will pull for requests just fine when there are no jobs scheduled.  Once you submit a job, the 'Worker' crashes with a Python file/dir not found or Permission denied message.  (If this is the case, remove (or rename for safe keeping) the manager.sqlite file, and re-run the manager.  It will then re-prompt you for the path's.  Then I ctrl-c out and restart just to be safe.)

2.  If you are using Windows, I found it to be less tolerant to changes like starting/stopping/deleting jobs, computer going into power saving mode...etc than Linux or OS X.  Basically I would recommened restarting any of the Flamenco services in Windows to make sure everything is kosher.

--Shaun

**Comment by peppelinux** [comment]
Thank you Shaun,
I just need to understand how to submit a new job through dashboard.
Can you help me please ?
:)

**Comment by binarypearl** [comment]
What you have to do, is get the render_flamenco.py staged on github here:  https://github.com/armadillica/flamenco/tree/master/plugins/blender

In Blender:  File -> User Preferences
Click on the 'Install from File' button.
Locate the render_flamenco.py that you saved on your computer.
Then in the Upper left-hand corner of the User Preferences, there is a search filed.  Start typing in 'Flamenco'.  Enable the add-on by clicking on the checkbox all the way to the right.
Now in the tool-bar (the left-most pane in the 3D View), there is a new tab called 'Flamenco'.  Click on that.  At first there one be one button, "Update Flamenco info".  Click on that.
That should hopefully find your setup, including your 'Manager'.
Now most of the default settings are what you probably want, shy of 'File Format' (I use PNG).
Then click on the "Save and Send" button
Then go to the 'Dashboard', and click reload button or refresh page.  
Then click on the checkbox with the new job, then click the Start button.
If all goes to plan, your workers should start printing lots of output as it renders.

Hope that helps.

--Shaun

**Comment by peppelinux** [comment]
Thank you Shaun,
All of this will be a good part of the documentation, do you agree ? :)
I use the farm via a VPN tunnel so I have to change at line 116

    flamenco_server = StringProperty(
        name="Flamenco Server URL",
        default="http://192.168.x.y:9999",
        options={'HIDDEN', 'SKIP_SAVE'})

then
    aptitude install bam lua52

but
    "Error running BAM. Is it installed?"

because, from terminal the bam command returns 1:
    bam: error opening 'bam.lua'

new issue :( ?!
    https://github.com/matricks/bam/issues/83

**Comment by fsiddi** [comment]
What is `bam lua52`?
Can you `pip3 install blender-bam` and type `bam` in your cli?

**Comment by peppelinux** [comment]
It could be usefull to have this information in the Core dependencies documentation of Readme.md
For ubuntu/debian
    aptitude install python3-pip
    pip3 install blender-bam

Awesome, it works but when I send my scene through flamenco plugin via blender-bam I see the job in Pause, every frames slice is in "Waiting". Clicking on the Job

from the logs side I read from server:
INFO:werkzeug:127.0.0.1 - - [09/Sep/2015 01:09:02] "PUT /tasks/1/status HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [09/Sep/2015 01:09:05] "GET /tasks/generate?worker=maker&uuid=b544528e54d511e59b02001cc4936120 HTTP/1.1" 404 -


from manager:
DEBUG:root:Scheduling
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:requests.packages.urllib3.connectionpool:"GET /tasks/generate?worker=goose&uuid=b544528e54d511e59b02001cc4936120 HTTP/1.1" 404 3
INFO:werkzeug:127.0.0.1 - - [09/Sep/2015 01:10:08] "GET /tasks/compiled/0?worker=goose HTTP/1.1" 400 -
INFO:werkzeug:192.168.27.10 - - [09/Sep/2015 01:10:08] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.27.10 - - [09/Sep/2015 01:10:08] "POST /workers HTTP/1.1" 204 -
DEBUG:root:Scheduling
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:requests.packages.urllib3.connectionpool:"GET /tasks/generate?worker=maker&uuid=b544528e54d511e59b02001cc4936120 HTTP/1.1" 404 3
INFO:werkzeug:192.168.27.10 - - [09/Sep/2015 01:10:09] "GET /tasks/compiled/0?worker=maker HTTP/1.1" 400 -

from workers:
Quering for a new task
[goose] No task available
[...]
Quering for a new task
[maker] No task available

If I delete this job from the dashboard, when I post it again I get, from blender stdout

Creating BAM archive at /tmp/jobfile_00df2474-5677-11e5-a86f-bc5ff4f4d0d9.zip
    
    scanning deps: b'/media/wert/storage1/blenders/blenders/car_sport_render.blend'...
      blend:       b'/media/wert/storage1/blenders/blenders/car_sport_render.blend'
      exclude:     b'/media/wert/Models/Cars/Ferrari_599_GTB/textures/concrete_wetmap.jpg'
      exclude:     b'/media/wert/Models/Cars/Ferrari_599_GTB/textures/ConcreteFloors0053_35_M.jpg'
      exclude:     b'/media/wert/Models/Cars/Ferrari_599_GTB/textures/ConcreteFloors0053_35_M_bump.jpg'
      exclude:     b'/media/wert/Models/Cars/Ferrari_599_GTB/textures/ferrari_horse_diffuse.png'
      exclude:     b'/media/wert/Models/Cars/Ferrari_599_GTB/textures/metal-lattice-01_o100.jpg'
    
    archiving: 1 files
      copying: b'/tmp/__blendfile_temp__/car_sport_render.blend@' -> <archive>
      written: b'/tmp/jobfile_00df2474-5677-11e5-a86f-bc5ff4f4d0d9.zip'
    Created a 1.28 MB BAM archive
    Traceback (most recent call last):
      File "/home/wert/.config/blender/2.75/scripts/addons/render_flamenco.py", line 344, in execute
        r = r.json()
      File "/home/wert/Progs/blender-2.75a-linux-glibc211-x86_64/2.75/python/lib/python3.4/site-packages/requests/models.py", line 797, in json
        return json.loads(self.text, **kwargs)
      File "/home/wert/Progs/blender-2.75a-linux-glibc211-x86_64/2.75/python/lib/python3.4/json/__init__.py", line 318, in loads
        return _default_decoder.decode(s)
      File "/home/wert/Progs/blender-2.75a-linux-glibc211-x86_64/2.75/python/lib/python3.4/json/decoder.py", line 343, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/wert/Progs/blender-2.75a-linux-glibc211-x86_64/2.75/python/lib/python3.4/json/decoder.py", line 361, in raw_decode
        raise ValueError(errmsg("Expecting value", s, err.value)) from None
    ValueError: Expecting value: line 1 column 1 (char 0)
    
    location: <unknown location>:-1
    
    location: <unknown location>:-1

The problem is that the location of the blend file is
    /media/wert/storage1/blenders/blenders/car_sport_render.blend

but it scans this inexistent location
    b'/media/wert/Models/Cars/Ferrari_599_GTB/'

Selecting Bake Anim cache I get
    Traceback (most recent call last):
      File "/home/wert/.config/blender/2.75/scripts/addons/render_flamenco.py", line 411, in draw
      if obj.cache_library:
    AttributeError: 'Object' object has no attribute 'cache_library'

 Where's the fault ?

**Comment by binarypearl** [comment]
On the 'bam' topic, there is another package (at least on ubuntu based systems) called ‘bam – fast and flexible build system’, which is not related at all to 'BAM - Blender Asset Manager'.  But the name of binary is still the same.  I didn't realize there was a difference until I started looking at the Flamenco code and realized it was calling options that didn't exist in the ubuntu 'bam'.

As far as this latest issue, I didn't run into this one so I'm not sure what's happening, but I can take a couple guesses.

1.  I would recommend restarting all of the services, just to give you a clean slate...however I would do this after everything I describe below.

2.  I didn't have to tweak the flamenco_render.py, but I was running my blender instance on the same linux server that is running all 4 Flamenco components.

However...I got to thinking.  In each for the 4 components folders, there is an application/config.py.example file.

On my linux server, I didn't modify any of these.  But on my 'Workers' on all other systems, I copy the config.py.example as config.py.  I then change 'FLAMENCO_MANAGER' to point to the 'Manager' on the Linux master.

For example:
My Linux Manager runs on 192.168.1.4:7777

On my OS X laptop:
cd /Applications/flamenco-master/flamenco/worker/application/
cp config.py.example config.py
vim config.py and change the 'FLAMENCO_MANAGER' line to point to your Manager.  By default it points to localhost:7777.
Ex:  FLAMENCO_MANAGER = '192.168.1.4:7777'

Unrelated side node:  I also changed the TMP_FOLDER = "/tmp",  The default OS X location is some ridiculous long path, and I wanted it closer to what I was doing in Linux.  Anyway... 

So if you haven't done this, then your Workers would be pointing to a local Manager, in which they would never get any jobs, which would explain why they are still polling for jobs and not seeing anything.

Ah, I was thinking.  I was surprised in my mind why the 'Worker' on your main master wouldn't pick up jobs (assuming you are doing this).  But you said something about needing to change the ip address because of VPN.  So assuming that's the case, I think you will have to do what I just described above on the 'Worker' on your master system.  I didn't have to do that because I'm just running a local network, where localhost responds just fine.  

Hope this helps you get further.

--Shaun

**Comment by peppelinux** [comment]
Sorry if I am late :)

I found a new exception worker side

Extracting /tmp/flamenco-worker/1/taskfile_1.zip
Fetching support file 1
Extracting /tmp/flamenco-worker/1/tasksupportfile_1.zip
Fetching dependency http://127.0.0.1:7777/static/storage/1/dependencies_1.zip
Extracting /tmp/flamenco-worker/1/dependencies.zip
Removing bad zipfile /tmp/flamenco-worker/1/dependencies.zip
ERROR:root:Not a ZipFile
200
Running:
/home/wert/Progs/blender-2.75a-linux-glibc211-x86_64/
--enable-autoexec
-noaudio
--background
/tmp/flamenco-worker/1/1//caz_divano.blend
--render-output
/tmp/flamenco-worker/1/output/1/#####
--python
/tmp/flamenco-worker/1/1//pre_render.py
--render-format
EXR
-f
1
Traceback (most recent call last):
  File "manage.py", line 67, in <module>
    manager.run()
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/wert/Progs/Flamenco.io/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 52, in runserver
    controllers.worker_loop()
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/worker/application/controllers.py", line 273, in worker_loop
    execute_task(task, files)
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/worker/application/controllers.py", line 759, in execute_task
    run_blender_in_thread(options)
  File "/home/wert/Progs/Flamenco.io/flamenco/flamenco/worker/application/controllers.py", line 528, in run_blender_in_thread
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

Running it as root same result.
What about "ERROR:root:Not a ZipFile" ? :(

**Comment by peppelinux** [comment]
My fault, as explained here https://github.com/armadillica/flamenco/issues/155

**Comment by antonvdh** [comment]
I still get Manager: TypeError: : tuple indices must be integers, not str  
How can I solve this.

**Comment by antonvdh** [comment]
./manage.py runserver
INFO:alembic.migration:Context impl SQLiteImpl.
INFO:alembic.migration:Will assume non-transactional DDL.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.178.18
DEBUG:requests.packages.urllib3.connectionpool:"POST /managers HTTP/1.1" 500 51
DEBUG:root:STATUS CODE: 500
Traceback (most recent call last):
  File "./manage.py", line 106, in <module>
    manager.run()
  File "/usr/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "./manage.py", line 96, in runserver
    setup_register_manager()
  File "./manage.py", line 88, in setup_register_manager
    register_manager(app.config['PORT'], app.config['NAME'], has_virtual_worker)
  File "/srv/www/htdocs/flamenco/flamenco/manager/application/__init__.py", line 104, in register_manager
    token = Setting(name='token', value=r['token'])
TypeError: <flask_script.commands.Command object at 0x7f1b6c7637d0>: tuple indices must be integers, not str
