### ISSUE TITLE
OS X: Error running BAM. Is it installed?

### ISSUE THREAD

**Issue by philnelson** [armadillica/flamenco#176]
Following the instructions in the README.md file, I cannot get the OS X version of blender to recognize that BAM is installed. I have gotten the whole stack running, dashboard shows up, no errors anywhere.

I ran `sudo pip3 install blender-bam` and it worked fine, but I still get "Error running BAM. Is it installed?" when I attempt to click the "Save and Send" button in the Flamenco plugin.

**Comment by philnelson** [comment]
I've isolated this error to the line `subprocess.call(command)` in render_flamenco.py's `bamToRenderfarm` command. What's funny is I can run the command manually and it works fine. Only when trying via blender do I get this error.

**Comment by fsiddi** [comment]
Could you try to make a an empty Python file and do a subprocess call from there?

**Comment by philnelson** [comment]
It appears that the plugin is attempting to use relative paths, but Blender on OS X doesn't like this. If I modify it it to be absolute, it works. I imagine it's something with python paths? Example:

Doesn't Work:
`
subprocess.call(["bam", "pack"])
`

Works as expected:
`
subprocess.call(["/usr/local/bin/bam", "pack"])
`

**Comment by fsiddi** [comment]
Interesting. Could you try with `shell=True`?
I'm using OSX but I have not had this problem recently. Which version of Python are you using?

**Comment by philnelson** [comment]
With `shell=True`:

`pack: bam: command not found`

**Comment by EVMosaic** [comment]
Hey, I ran into this same issue a while back, and unfortunately don't appear to have documented my solutions anywhere so I can't remember what actually ended up fixing it for me, but here's a few things I do remember doing trying to get it working, your mileage may vary. Also In my setup I'm running OSX as a worker and Linux as the Manager/Server.

1) Make sure the path to blender is set on the server, I ended up manually editing this in the database because I couldn't get the preference files to import properly or the web interface to update. This probably isn't it if you set everything up properly at the beginning, but its a quick check/fix.

2) Check your environment variables. I could be wrong on this so someone correct me if I am, but I believe Blender has its own installation of python that doesn't have access to your standard PATH variables. I was able to check this by running bam in Terminal and seeing desired output and then again in the Blender Python interpreter and getting the not installed message. I think I solved this by putting BAM into the 3rd party scripts folder on Blender? This is my best guess for what fixed it. 

3) This was a really esoteric problem that ended up stumping me for a few days, and I haven't tried to duplicate it since so again take it with a grain of salt, but after getting everything setup on a Windows machine I was getting the same error and I couldn't get the worker to connect. Turns out to my blender file was stored on my C: drive but using assets I had stored on my E: drive where I keep texture libraries and such. I had to go in and edit some standard functions to output more info but this was definitely where the error was coming from. Moving all assets to the C: drive and purging all references from the blend file to the previous locations made the worker start up for me.

I wish I took better notes, but I was working under a tight deadline at the time and abandoned documenting my process at a certain point and went with the lets see what sticks approach. Hopefully something in there helps.

**Comment by peppelinux** [comment]
Is BAM installed in virtualenv environment or system-wide (/usr/local/lib/python3) ?

**Comment by djazo** [comment]
I added configuration to flamenco addon to give executable path to bam.  IMO best workaround.
[render_flamenco_py.diff.zip](https://github.com/armadillica/flamenco/files/242253/render_flamenco_py.diff.zip)

**Comment by djazo** [comment]
Thing is, macOS doesn't allow adding /usr/local/bin to the PATH (or anything!) anymore when running programs from Finder. That's why I did the patch for the blender addon, where you can configure bam location on addon. If you start blender from terminal, your PATH variable is passed correctly, and no extra configuration is needed.

@fsiddi remember? =)

**Comment by sybrenstuvel** [comment]
I'm closing this issue, since it relates to the old, now-obsolete version of Flamenco. Read about the new Flamenco 2.0 at https://flamenco.io/.
