### ISSUE TITLE
Document taking out `--factory-startup` to allow GPU for rendering (and other userprefs-dependent things)

### ISSUE THREAD

**Issue by binarypearl** [armadillica/flamenco#204]
The good news is that I have multiple nodes rendering.

The problem is that on the 2nd worker, it's not using the GPU for rendering.  I can tell because the CPU is really old and slow, and my first worker finishes all of it's tasks before the 2nd worker finishes 1 task.

First worker:  (which also runs the manager and is the computer I kick the job off from) is using the GPU.  I can tell by the very scientific method of watching the temperature of the GPU go up as soon as I click 'Render on Flamenco'.  command to see temp:  `nvidia-smi -a | grep Temp`

Second worker:  Only runs the worker component.  I tried opening the startup file and saving it with the GPU enabled.  I also tried manually loading the actual blend file first, but those didn't have any effect.  And I just realized since the manager yaml file has the --factory-startup flag with the blender binary that will bypass the normal startup file anyway.  

Any ideas on how to get the 2nd worker to use the GPU for rendering?

--Shaun

**Comment by binarypearl** [comment]
I found a work-around.  In the manager's flamenco-manager.yaml file, I took out the '--factory-startup' option in the variables -> blender -> linux entry, and then it started using the gpu for rendering.  Not sure if this is the correct solution, but it works for now.

I opened up the .blend file during a render on the worker in question, and noticed that it did have the GPU Compute option set, which is what prompted me to look at taking out that option.

--Shaun

**Comment by sybrenstuvel** [comment]
This is exactly the reason why we have `--factory-startup` in that variables section, so that you can take it out. Previously it was hard-coded (because we always use that here at the Blender Studio) so it was a lot harder back then ;-)

We decided to leave the `--factory-startup` in the example file, so that it's clear you can pass CLI options to Blender there, and not just point it to the executable.

We'll include this in the documentation, so that it's easier to figure out for future users.

**Comment by sybrenstuvel** [comment]
Resolved in 8938cedb80c6641c8ff60cafa2997d190a1aa96c
