### ISSUE TITLE
Latest rendered image error - exit status 4

### ISSUE THREAD

**Issue by jhowe-3d** [armadillica/flamenco#224]
I can't seem to get the last rendered image to generate. The manager is successfully identifying the image but comes back with "exit status 4" 

```
[37mDEBU[0m[2018-03-15T13:15:18-04:00] ImageWatcher: image file written: \\SERVER\Flamenco\TempImages\Variable02__intermediate\000531.jpg
[36mINFO[0m[2018-03-15T13:15:18-04:00] ConvertAndForward: Converting \\SERVER\Flamenco\TempImages\Variable02__intermediate\000531.jpg to static\latest-image.jpg
[31mERRO[0m[2018-03-15T13:15:18-04:00] ConvertAndForward: error converting \\SERVER\Flamenco\TempImages\Variable02__intermediate\000531.jpg: exit status 4
```

I don't think this is a permissions issue because I deleted static\latest-image.jpg and it still isn't working. I also am able to view the image (in this case 000531.jpg) so the JPEG appears to be valid. Any thoughts on why this is erroring out?

**Comment by sybrenstuvel** [comment]
Shares on `\\SERVER` are always troublesome. Map a drive letter and use that, instead.

If that doesn't help, at least let us know the OS you're working on, and which version of Flamenco Manager and Flamenco Worker you're using.

**Comment by jhowe-3d** [comment]
Worked on this and found that the file is reading properly accessing folder various ways (http, drive letter, server name, etc.). It turns out that the problem is with the call to convert the image in [fswatcher_middle_go](https://developer.blender.org/source/flamenco-manager/browse/master/flamenco/fswatcher_middle.go;7df9e8820685de8eb2d00daf02b6434c6752f018$25).
It looks like this is expecting to see ImageMagick installed, as it is trying to call the convert.exe command from that, but I didn't have this installed. I installed ImageMagick and copied the convert.exe and associated DLLs to the flamenco folder and the last rendered image is now working.

Am I correct in assuming that ImageMagick is a requirement for this feature to work?

**Comment by sybrenstuvel** [comment]
Yes, ImageMagick is required for this feature to work, which is why installing it is listed as [the first step in the README.md file](https://github.com/armadillica/flamenco-manager#getting-started). However, this is not mentioned in the [documentation on flamenco.io](https://www.flamenco.io/docs/user_manual/installation/#manager-installation), so I'll keep this ticket open to remind us to change that.

> It calls the Windows convert disk command instead.

That is not so nice, but the decision to name such an unusual tool (How often do you convert disks? I don't even know what it means) with such a generic name begs for it to be called sooner or later.

> I also am running flamenco manager at highest privileges.

I don't recommend running Flamenco Manager at elevated privileges, as we cannot guarantee it won't trash your machine (for example by calling the disk conversion utility and actually succeeding). Just run it as a regular user, and make sure that that user has write access to the locations it needs to write to.

> maybe we could add a variable to the config file to store the path to the convert executable?

The path to the `convert.exe` binary is expected to be on the `PATH` environment variable, as it is by default on Linux-based systems.  We're open to pull requests that add such a setting, but be sure to also cover documentation, the web interface for the setup mode, and possibly unit tests.

**Comment by sybrenstuvel** [comment]
> this is not mentioned in the documentation on flamenco.io, so I'll keep this ticket open to remind us to change that.

I've just added this to the documentation, so I'll close this ticket. Please feel free to reply and keep the discussion going -- the "Closed" status just indicates that there is no immediate action required by us.

**Comment by jhowe-3d** [comment]
It looks like ImageMagick is moving or has moved from "convert" to "magick" as their [command line tool](http://www.imagemagick.org/script/command-line-processing.php), so there may be an opportunity to update the call to convert the image.
