### ISSUE TITLE
sign-on error running latest worker in Windows 10

### ISSUE THREAD

**Issue by binarypearl** [armadillica/flamenco#230]
I'm getting back into setting up the latest version of Flamenco, and am having trouble starting flamenco-worker.exe in Windows 10:

![image](https://user-images.githubusercontent.com/839047/51093376-f5418a80-1770-11e9-8fea-6f0dda4a0465.png)

At the command line it's saying error 401.  If I go to http://192.168.1.153:8083/sign-on in Chrome it says 'This page isn't working' and gives error 405.  I upgraded to the latest version of python (3.7.2 64 bit).  I also tried the 32 bit version, same issue, but opted to leave only the 64 bit version installed.

I can get to the root of http://192.168.1.153:8083 just fine in a web browser.

I originally realized I hadn't configured flamenco-manager.yaml for the Windows paths.  I have since corrected those and restarted the manger, but am still getting the same issue.  The output of the manager shows:

WARN[2019-01-13T20:42:58-05:00] Error fetching hashed password                error="not found"

Do you know what might be happening here?  If there are any other details that I can provide, please let me know, thanks! 

(FYI, I was able to get 3 workers running successfully on Ubuntu 18.04).

**Comment by sybrenstuvel** [comment]
This is what happens when the worker tries to authenticate with an account that doesn't exist any more. My bet is that you upgraded Flamenco Manager without moving the database to the new install. Either configure Flamenco Manager to place the database outside the program directory, or move it from the old to the new version when you upgrade.

Alternatively, run the worker with `flamenco-worker - -reregister` and it'll discard its credentials and register as a new worker.

**Comment by binarypearl** [comment]
The --reregister flag worked, thanks!  I had used this computer/OS with prior versions of Flamenco, so it must have been picking up something from an old version.
